name: unistate_adapter
description: "A Flutter package that provides adapters to convert various state management solutions to ValueListenable interface."
version: 0.0.1
homepage: https://github.com/aissat/unistate
repository: https://github.com/aissat/unistate

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"
resolution: workspace

dependencies:
  flutter_bloc: ^8.1.6
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0